/**
 * Seed values for billing plans. Upserted by the seed script.
 * Runtime reads prices from the `Plan` table (super-admin can edit them).
 */
import { PlanInterval } from "@prisma/client";

export const PLAN_SEED = [
  {
    code: "trial",
    name: "Free trial",
    tagline: "Try everything, no card",
    description: "14 days on us — every feature unlocked.",
    interval: PlanInterval.MONTH,
    sortOrder: 0,
    priceCents: 0,
    compareAtPriceCents: 0,
    currency: "PKR",
    maxBranches: 1,
    maxStaff: 5,
    maxMenuItems: 100,
    maxMonthlyOrders: 1000,
    whatsappEnabled: true,
    deliveryZonesEnabled: true,
    customDomainEnabled: false,
    prioritySupport: false,
    apiEnabled: false,
    isActive: true,
    isFeatured: false,
    isPublic: false,
  },
  {
    code: "starter",
    name: "Starter",
    tagline: "For solo cafes",
    description: "Single outlet, the essentials to run a kitchen online.",
    interval: PlanInterval.MONTH,
    sortOrder: 1,
    priceCents: 299_900, // PKR 2,999
    compareAtPriceCents: 499_900,
    currency: "PKR",
    maxBranches: 1,
    maxStaff: 5,
    maxMenuItems: 100,
    maxMonthlyOrders: 1000,
    whatsappEnabled: false,
    deliveryZonesEnabled: true,
    customDomainEnabled: false,
    prioritySupport: false,
    apiEnabled: false,
    isActive: true,
    isFeatured: false,
    isPublic: true,
  },
  {
    code: "growth",
    name: "Growth",
    tagline: "Most popular",
    description: "Multi-branch, WhatsApp, deals — everything you need to grow.",
    interval: PlanInterval.MONTH,
    sortOrder: 2,
    priceCents: 699_900, // PKR 6,999
    compareAtPriceCents: 999_900,
    currency: "PKR",
    maxBranches: 5,
    maxStaff: 25,
    maxMenuItems: 500,
    maxMonthlyOrders: 10_000,
    whatsappEnabled: true,
    deliveryZonesEnabled: true,
    customDomainEnabled: false,
    prioritySupport: false,
    apiEnabled: false,
    isActive: true,
    isFeatured: true,
    isPublic: true,
  },
  {
    code: "enterprise",
    name: "Enterprise",
    tagline: "Chains & franchises",
    description: "Unlimited branches, custom domain, priority support, API access.",
    interval: PlanInterval.MONTH,
    sortOrder: 3,
    priceCents: 1_499_900, // PKR 14,999
    compareAtPriceCents: 0,
    currency: "PKR",
    maxBranches: 9999,
    maxStaff: 9999,
    maxMenuItems: 99_999,
    maxMonthlyOrders: 999_999,
    whatsappEnabled: true,
    deliveryZonesEnabled: true,
    customDomainEnabled: true,
    prioritySupport: true,
    apiEnabled: true,
    isActive: true,
    isFeatured: false,
    isPublic: true,
  },
  {
    code: "lifetime",
    name: "Lifetime",
    tagline: "Buy once, own forever",
    description: "One-time payment. All Enterprise features. No monthly bills.",
    interval: PlanInterval.LIFETIME,
    sortOrder: 4,
    priceCents: 14_999_900, // PKR 149,999
    compareAtPriceCents: 29_999_900,
    currency: "PKR",
    maxBranches: 9999,
    maxStaff: 9999,
    maxMenuItems: 99_999,
    maxMonthlyOrders: 999_999,
    whatsappEnabled: true,
    deliveryZonesEnabled: true,
    customDomainEnabled: true,
    prioritySupport: true,
    apiEnabled: true,
    isActive: true,
    isFeatured: false,
    isPublic: true,
  },
] as const;

export const TRIAL_DAYS = 14;
